name = "whut-resource"
pages_build_output_dir = "."
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "whut-resource-db"
database_id = "ca8c5d47-9f09-454e-82d3-411a2aa8e9ea"

[[r2_buckets]]
binding = "R2_bucket"
bucket_name = "resource"
