name = "whut-resource-ai-consumer"
main = "index.js"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
account_id = "f78fada5fe63d8a55e2b2405879203bf"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "whut-resource-db"
database_id = "ca8c5d47-9f09-454e-82d3-411a2aa8e9ea"

[[r2_buckets]]
binding = "R2_bucket"
bucket_name = "resource"

[[vectorize]]
binding = "VECTORIZE"
index_name = "whut-resource-index"

[[queues.producers]]
binding = "AI_QUEUE"
queue = "whut-resource-ai"

[[queues.producers]]
binding = "FILE_QUEUE"
queue = "whut-resource-file"

[[queues.consumers]]
queue = "whut-resource-ai"
max_batch_size = 1
max_batch_timeout = 30
max_retries = 3

[[queues.consumers]]
queue = "whut-resource-file"
max_batch_size = 1
max_batch_timeout = 30
max_retries = 3

[durable_objects]
bindings = [
    { name = "DOWNLOAD_LOGGER", class_name = "DownloadLogger", script_name = "whut-resource-do" }
]

[vars]
AI_MODEL = "deepseek-v4.1-flash"
